baseURL = 'shawnjacobsen.com'
languageCode = 'en-us'
title = 'Shawn Jacobsen'
theme = "m10c"

[params]
author = "Shawn Jacobsen"
description = "Software Engineer"
avatar = 'images/shawn_jacobsen_headshot.jpg'
favicon = 'favicon.ico'